name: UMA SDK Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "release/v1.0" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Build and lint
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: uma-sdk:assemble
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Test and Lint
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: check
